import Head from "next/head";
import Header from "../../components/Header";
import { FaMapMarkerAlt } from "react-icons/fa";
import Button from "../../components/Button";
import { IoPencil } from "react-icons/io5";
import ProductCheckoutCard from "../../components/ProductCheckoutCard";

export default function Cart() {
  return (
    <div className="">
      <Head>
        <title>Heat & Eat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="flex justify-center">
          <div className="w-[360px] bg-white h-screen relative">
            <Header title={"Cart"} />
            <div className="divide-y-[1px] divide-black">
              <div className="px-6 pb-2">
                <div className="flex gap-2">
                  <FaMapMarkerAlt className="text-[#991E23] text-2xl" />
                  <div className="mt-1">
                    <p className="text-xs">Delvery Address</p>
                    <div className="flex gap-2 items-start">
                      <p className="text-xs mt-1">
                        Dastin | (+62) 8123456789 Jl. Old Water Lake No. 11,
                        Dago, Kec. Coblong COBLONG, KOTA BANDUNG, JAWA BARAT,
                        40135
                      </p>
                      <IoPencil className="text-[#C4C4C4] text-3xl" />
                    </div>
                  </div>
                </div>
              </div>
              <div className="px-6 py-2">
                <div className="flex gap-2">
                  <input type="checkbox" />
                  <p className="text-xs">Choose all</p>
                </div>
              </div>

              {/* Toko 1 */}
              <div className="px-6 py-2 flex flex-col gap-3">
                <div className="flex gap-2">
                  <input type="checkbox" />
                  <p className="text-xs font-bold">Toko Suka Majumundur</p>
                </div>
                <div className="">
                  <div className="flex gap-2">
                    <input type="checkbox" />
                    <ProductCheckoutCard />
                  </div>
                </div>
                <div className="">
                  <div className="flex gap-2">
                    <input type="checkbox" />
                    <ProductCheckoutCard />
                  </div>
                </div>
              </div>

              {/* Toko 2 */}
              <div className="px-6 py-2 flex flex-col gap-3">
                <div className="flex gap-2">
                  <input type="checkbox" />
                  <p className="text-xs font-bold">Toko Suka Majumundur</p>
                </div>
                <div className="">
                  <div className="flex gap-2">
                    <input type="checkbox" />
                    <ProductCheckoutCard />
                  </div>
                </div>
              </div>
            </div>
            <div className="absolute bottom-0 w-full z-10">
              <div className="px-6 h-[40px] flex items-center justify-between border-[1px] border-black">
                <p className="text-xs">Calories:</p>
                <p className="font-bold text-xs">0 cal</p>
              </div>
              <div className="px-6 h-[70px] flex items-center justify-between">
                <div className="w-1/3">
                  <div className="flex justify-between items-center">
                    <p className="text-xs">Total</p>
                    <p className="bg-[#C8D7D2] px-1 rounded-full text-[8px]">
                      +15 Heapay Points
                    </p>
                  </div>
                  <p className="text-xl text-[#991E23] font-bold">Rp150.000</p>
                </div>
                <div className="flex">
                  <button className="text-base px-6 py-1 rounded-full text-white bg-[#991E23]">
                    <a href="/cart/checkout">Checkout</a>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
