import Head from "next/head";
import Header from "../components/Header";
import { IoChevronBackOutline } from "react-icons/io5";
import { IoChevronForwardCircleOutline } from "react-icons/io5";
import { IoPencil } from "react-icons/io5";
import Button from "../components/Button";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Heat & Eat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=""></main>

      <footer className=""></footer>
    </div>
  );
}
