import Head from "next/head";
import { useRouter } from "next/router";
import Header from "../../components/Header";
import { FaShoppingCart } from "react-icons/fa";
import ReviewCard from "../../components/ReviewCard";
import CheckoutBar from "../../components/CheckoutBar";

export default function ProductDetails() {
  const router = useRouter();
  const { name } = router.query;

  return (
    <div className="">
      <Head>
        <title>Heat & Eat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="flex justify-center">
          <div className="w-[360px] bg-white h-screen relative">
            <Header
              className="text-[#991E23]"
              title={"Product Details"}
              rightIcon={<FaShoppingCart />}
            />
            <div className="flex flex-col items-center">
              <div className="w-[320px]">
                <img src="/salman.png" className="w-full" alt="" />
                <div className="mt-4 divide-y-2 divide-solid divide-black space-y-4">
                  <div className="flex flex-col gap-2">
                    <h2 className="capitalize font-bold">
                      {name && name.replace(/-/g, " ")}
                    </h2>
                    <p className="text-xs">
                      Nikmatnya sajian Salmon with Fried Rice menggoda selera
                      dengan kombinasi salmon panggang yang lembut dan nasi
                      goreng yang gurih. Setiap gigitan memanjakan lidah dengan
                      perpaduan cita rasa yang sempurna.
                    </p>
                    <div className="flex items-center justify-between">
                      <p className="font-bold">Rp50.000</p>
                      <p>300 kcal</p>
                    </div>
                  </div>
                  <div className="pt-4 flex items-center justify-between">
                    <div className="">
                      <p className="text-sm font-bold">Toko Suka Majumundur</p>
                      <p className="text-xs">Kota Bandung</p>
                    </div>
                    <button className="border-[#991E23] text-[#991E23] font-bold border-2 px-3 py-[2px] rounded-md flex">
                      <a className="text-[10px]" href="">
                        Visit Store
                      </a>
                    </button>
                  </div>
                  <div className="pt-4">
                    <h2 className="font-bold">Reviews</h2>
                    <div className="mt-2">
                      <ReviewCard />
                    </div>
                  </div>
                </div>
              </div>
              <div className="absolute bottom-0 w-full z-10">
                <CheckoutBar />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
