import Head from "next/head";
import Header from "../components/Header";
import { IoChevronBackOutline } from "react-icons/io5";
import { IoChevronForwardCircleOutline } from "react-icons/io5";
import { IoPencil } from "react-icons/io5";
import Button from "../components/Button";
import { FaUserLarge } from "react-icons/fa6";
import { IoIosSearch } from "react-icons/io";
import { IoNotifications } from "react-icons/io5";
import HeaPayPill from "../components/HeaPayPill";
import MenuCard from "../components/MenuCard";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Heat & Eat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="flex justify-center">
          <div className="w-[360px] bg-white h-screen relative">
            <div className="absolute flex items-center w-full justify-between text-xl p-3 mb-8 gap-2">
              <div className="flex items-center flex-grow rounded-full gap-2 bg-[#F3F2F0] text-base px-2 py-1 text-[#949494]">
                <IoIosSearch />
                <input
                  type="text"
                  placeholder="Search"
                  className="w-full bg-[#F3F2F0] focus:outline-0"
                />
              </div>
              <div className=" rounded-full p-[8px] bg-white text-[#991E23]">
                <IoNotifications className="text-base" />
              </div>
              <div className=" rounded-full p-[8px] bg-white text-[#991E23]">
                <FaUserLarge className="text-base" />
              </div>
            </div>
            <div className="">
              <img src="/Poster.png" className="" alt="" />
            </div>
            <div className="-translate-y-8">
              <HeaPayPill />
            </div>
            <div className="mx-7">
              <h2 className="font-bold text-xl mb-4">{`Today's Menu Recommendation!`}</h2>
              <div className="flex gap-2">
                <MenuCard />
                <MenuCard />
                <MenuCard />
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className=""></footer>
    </div>
  );
}
