import Head from "next/head";
import Header from "../../../components/Header";
import { FaMapMarkerAlt } from "react-icons/fa";
import { IoPencil } from "react-icons/io5";
import FinalProductCheckoutCard from "../../../components/FinalProductCheckoutCard";

export default function Checkout() {
  return (
    <div className="">
      <Head>
        <title>Heat & Eat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="flex justify-center">
          <div className="w-[360px] bg-white h-screen relative">
            <Header title={"Cart"} />
            <div className="px-6 flex flex-col gap-4">
              {/* Alamat */}
              <div className="bg-[#F3F2F0] px-5 py-3 rounded-xl">
                <p className="font-bold text-xs">Delvery Address</p>
                <p className="text-xs mt-1">Dastin</p>
                <p className="text-xs mt-1">(+62) 8123456789</p>
                <p className="text-[10px] mt-1">
                  Jl. Old Water Lake No. 11, Dago, Kec. Coblong COBLONG, KOTA
                  BANDUNG, JAWA BARAT, 40135
                </p>
              </div>

              {/* Info Produk */}
              <div className="bg-[#F3F2F0] px-6 py-3 rounded-xl">
                <FinalProductCheckoutCard />
              </div>

              <div className="divide-y-[1px] divide-black">
                <h2 className="font-bold pb-2">Payment Details</h2>
                <div className="pt-2">
                  <div className="flex justify-between">
                    <p className="text-xs">Price</p>
                    <p className="text-xs">Rp50.000</p>
                  </div>
                  <div className="flex justify-between">
                    <p className="text-xs">Delivery</p>
                    <p className="text-xs">Rp10.000</p>
                  </div>
                  <div className="flex justify-between">
                    <p className="text-xs">Food Subtotal Discount</p>
                    <p className="text-xs">-Rp0</p>
                  </div>
                  <div className="flex font-bold justify-between">
                    <p className="text-xs">Payment Total</p>
                    <p className="text-xs">Rp60.000</p>
                  </div>
                </div>
              </div>
            </div>
            <div className="absolute bottom-0 w-full px-6 py-3 z-10">
              <button className="bg-[#991E23] py-1 text-white font-semibold rounded-full w-full">
                Checkout
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
